name: Release WOLServer

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 安装 musl 工具链
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: 编译静态二进制
        run: |
          musl-gcc -Os -static -o wolserver wolserver.c
          strip wolserver

      - name: 创建 GitHub Release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 上传 Release 组件
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./wolserver
          asset_name: wolserver-openwrt-x86
          asset_content_type: application/octet-stream
