name: Build WOLServer (C) for OpenWrt

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install musl toolchain
      run: sudo apt-get update && sudo apt-get install -y musl-tools

    - name: Compile with musl (静态链接)
      run: |
        musl-gcc -Os -static -o wolserver wolserver.c
        strip wolserver

    - name: Verify binary
      run: file wolserver

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: wolserver-openwrt-x86
        path: wolserver
