name: Build WOLServer (C)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Compile WOLServer
        run: |
          gcc -Os -o wolserver wolserver.c
          strip wolserver

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wolserver-openwrt-x86
          path: wolserver
