name: CI → Build & Release

on:
  push:
    branches: [ master ]
    tags:     [ 'v*' ]
  workflow_dispatch:

jobs:
  build:
    name: Build on branch
    if: startsWith(github.ref, 'refs/heads/master')  # 只有分支 push 时跑
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y musl-tools build-essential
      - run: |
          musl-gcc -Os -static -o wolserver wolserver.c
          strip wolserver
      - uses: actions/upload-artifact@v4
        with:
          name: wolserver-openwrt-x86
          path: wolserver

  release:
    name: Release on tag
    if: startsWith(github.ref, 'refs/tags/v')        # 只有 tag push 时跑
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 直接在这里重新编译一遍（替代 build job）
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools build-essential
      - name: Compile static binary
        run: |
          musl-gcc -Os -static -o wolserver wolserver.c
          strip wolserver

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag:     ${{ github.ref_name }}
          name:    Release ${{ github.ref_name }}
          artifacts: wolserver
          draft:   false
          prerelease: false
          overwrite:  true
