# 文件路径：.github/workflows/ci.yml
name: CI Build & Release

# 赋予 GITHUB_TOKEN 创建 Release 和上传资产的权限
permissions:
  contents: write

on:
  push:
    # 普通 push 到 master 时触发 “build” job
    branches: [ master ]
    # 推送以 v 开头的 tag 时同时触发 “build” 和 “release” job
    tags:     [ 'v*' ]
  workflow_dispatch:

jobs:
  build:
    name: Build WOLServer
    runs-on: ubuntu-latest
    outputs:
      artifact-name: wolserver
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools build-essential

      - name: Compile static binary
        run: |
          musl-gcc -Os -static -o wolserver wolserver.c
          strip wolserver

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-name }}
          path: wolserver

  release:
    name: Publish GitHub Release
    needs: build
    # 只有当触发来源是 tag（refs/tags/v*）时才执行
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-name }}
          path: .

      - name: Create Release and Upload Asset
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag:       ${{ github.ref_name }}
          name:      Release ${{ github.ref_name }}
          body:      Automated release of ${{ github.ref_name }}
          draft:     false
          prerelease:false
          artifacts: wolserver
          allowUpdates: true
