name: CI → Build & Release

on:
  push:
    branches: [ master ]     # 普通 push
    tags:     [ 'v*' ]       # 打 v* 标签时也触发
  workflow_dispatch:         # 支持手动触发

jobs:
  build:
    name: Compile WOLServer
    runs-on: ubuntu-latest
    outputs:
      binary: wolserver
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools build-essential

      - name: Build static binary
        run: |
          musl-gcc -Os -static -o wolserver wolserver.c
          strip wolserver

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: wolserver-openwrt-x86
          path: wolserver

  release:
    name: Publish Release on tag
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: wolserver-openwrt-x86
          path: .

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}       # 必填，否则会报 “Parameter token is required”
          tag_name: ${{ github.ref_name }}         # 比如 v1.0.0
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./wolserver
          asset_name: wolserver-openwrt-x86
          asset_content_type: application/octet-stream