# 文件：.github/workflows/ci.yml
name: CI Build & Release

permissions:
  contents: write   # 给 GITHUB_TOKEN 写 Release 的权限

on:
  push:
    branches: [ master ]    # 普通 push 只触发 build
    tags:     [ 'v*' ]      # 打 v* 标签时触发 build + release
  workflow_dispatch:        # 支持手动触发（默认只跑 build）

jobs:
  build:
    name: Build WOLServer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools build-essential

      - name: Compile static binary
        run: |
          musl-gcc -Os -static -o wolserver wolserver.c
          strip wolserver

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: wolserver
          path: wolserver

  release:
    name: Create Release on Tag
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')   # 仅 tag 事件才跑
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: wolserver
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name:   ${{ github.ref_name }}
          name:       Release ${{ github.ref_name }}
          files:      wolserver
