name: CI Build & Release

on:
  push:
    branches: [ master ]
    tags:     [ 'v*' ]
  workflow_dispatch:

jobs:
  build:
    name: Compile WOLServer
    runs-on: ubuntu-latest
    outputs:
      binary-path: wolserver
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools build-essential

      - name: Build static binary
        run: |
          musl-gcc -Os -static -o wolserver wolserver.c
          strip wolserver

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: wolserver-openwrt-x86
          path: wolserver

  release:
    name: Publish Release on Tag
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: wolserver-openwrt-x86
          path: .

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./wolserver
          asset_name: wolserver-openwrt-x86
          asset_content_type: application/octet-stream
